### PostgreSQL
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/loc?schema=public
    username: postgres
    password: changeme
  graphql:
    websocket:
      connection-init-timeout: 60s
      path: /graphql
### Logging
logging:
  level:
    io.r2dbc.postgresql.QUERY: INFO
    io.r2dbc.postgresql.PARAM: INFO
    com.demo.reactive.graphql: INFO

random-api:
  base-uri: https://dog.ceo/api/breeds/image/random
